//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabbles.OutlookAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tabbles.OutlookAddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building message to send to Confidential. Progress: {A} of {B}..
        /// </summary>
        public static string buildingMessageToSendToConfid {
            get {
                return ResourceManager.GetString("buildingMessageToSendToConfid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building message to send to Tabbles. Progress: {A} of {B}..
        /// </summary>
        public static string buildingMessageToSendToTabbles2 {
            get {
                return ResourceManager.GetString("buildingMessageToSendToTabbles2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering emails to send to Confidential. Emails found: {N}.
        /// </summary>
        public static string gatheringEmails {
            get {
                return ResourceManager.GetString("gatheringEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering emails to send to Tabbles. Emails found: {N}.
        /// </summary>
        public static string gatheringEmails2 {
            get {
                return ResourceManager.GetString("gatheringEmails2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LabelCancel {
            get {
                return ResourceManager.GetString("LabelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string LabelNo {
            get {
                return ResourceManager.GetString("LabelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string LabelOk {
            get {
                return ResourceManager.GetString("LabelOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string LabelYes {
            get {
                return ResourceManager.GetString("LabelYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string MenuOpenInTabbles2 {
            get {
                return ResourceManager.GetString("MenuOpenInTabbles2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string MenuSyncWithTabbles3 {
            get {
                return ResourceManager.GetString("MenuSyncWithTabbles3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string MenuTabblesSearch3 {
            get {
                return ResourceManager.GetString("MenuTabblesSearch3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string MenuTagUsingTabbles2 {
            get {
                return ResourceManager.GetString("MenuTagUsingTabbles2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The informations about your emails and their tags have been sent to {PRODUCT}. It might take time for {PRODUCT} to tag them all..
        /// </summary>
        public static string messageSyncSentToTabbles {
            get {
                return ResourceManager.GetString("messageSyncSentToTabbles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string MsgAreYouSure {
            get {
                return ResourceManager.GetString("MsgAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message from Tabbles add-in.
        /// </summary>
        public static string MsgCaptionTabblesAddIn {
            get {
                return ResourceManager.GetString("MsgCaptionTabblesAddIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidential is not running..
        /// </summary>
        public static string MsgConfidIsNotRunning3 {
            get {
                return ResourceManager.GetString("MsgConfidIsNotRunning3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t ask again..
        /// </summary>
        public static string MsgDontAskAgain {
            get {
                return ResourceManager.GetString("MsgDontAskAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to import all your existing email
        ///categorization into Tabbles?.
        /// </summary>
        public static string MsgDoYouWantToSync {
            get {
                return ResourceManager.GetString("MsgDoYouWantToSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        public static string MsgNoResultsFound {
            get {
                return ResourceManager.GetString("MsgNoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabbles is not running..
        /// </summary>
        public static string MsgTabblesIsNotRunning3 {
            get {
                return ResourceManager.GetString("MsgTabblesIsNotRunning3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email selected..
        /// </summary>
        public static string noEmailSelected {
            get {
                return ResourceManager.GetString("noEmailSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function is only available for emails..
        /// </summary>
        public static string notAnEmail {
            get {
                return ResourceManager.GetString("notAnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap open_in_tabbles_16_bmp {
            get {
                object obj = ResourceManager.GetObject("open_in_tabbles_16_bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap open_in_tabbles_16_mask {
            get {
                object obj = ResourceManager.GetObject("open_in_tabbles_16_mask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap open_in_tabbles_16_png {
            get {
                object obj = ResourceManager.GetObject("open_in_tabbles_16_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap open_in_tabbles_32 {
            get {
                object obj = ResourceManager.GetObject("open_in_tabbles_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Outlook_16x16_open {
            get {
                object obj = ResourceManager.GetObject("Outlook_16x16_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Outlook_16x16_tag {
            get {
                object obj = ResourceManager.GetObject("Outlook_16x16_tag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Outlook_32x32_open {
            get {
                object obj = ResourceManager.GetObject("Outlook_32x32_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Outlook_32x32_options {
            get {
                object obj = ResourceManager.GetObject("Outlook_32x32_options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Outlook_32x32_search {
            get {
                object obj = ResourceManager.GetObject("Outlook_32x32_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Outlook_32x32_sync {
            get {
                object obj = ResourceManager.GetObject("Outlook_32x32_sync", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Outlook_32x32_tag {
            get {
                object obj = ResourceManager.GetObject("Outlook_32x32_tag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap search_16_bmp {
            get {
                object obj = ResourceManager.GetObject("search_16_bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap search_16_mask {
            get {
                object obj = ResourceManager.GetObject("search_16_mask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap search_32 {
            get {
                object obj = ResourceManager.GetObject("search_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending message to {PRODUCT}....
        /// </summary>
        public static string sendingMessageToConfidential4 {
            get {
                return ResourceManager.GetString("sendingMessageToConfidential4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sync_with_tabbles_16_bmp {
            get {
                object obj = ResourceManager.GetObject("sync_with_tabbles_16_bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sync_with_tabbles_16_mask {
            get {
                object obj = ResourceManager.GetObject("sync_with_tabbles_16_mask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sync_with_tabbles_32 {
            get {
                object obj = ResourceManager.GetObject("sync_with_tabbles_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tag_using_tabbles_16_bmp {
            get {
                object obj = ResourceManager.GetObject("tag_using_tabbles_16_bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tag_using_tabbles_16_mask {
            get {
                object obj = ResourceManager.GetObject("tag_using_tabbles_16_mask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tag_using_tabbles_16_png {
            get {
                object obj = ResourceManager.GetObject("tag_using_tabbles_16_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tag_using_tabbles_32 {
            get {
                object obj = ResourceManager.GetObject("tag_using_tabbles_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will import all the emails contained in the currently selected folder ({FOLDER}) and subfolders, together with their tags, into {PRODUCT}. New tags will be created in {PRODUCT} if needed. If an email is already tagged in {PRODUCT}, its tags will be updated. This can take a long time. Do you want to continue?.
        /// </summary>
        public static string thisWillImport2 {
            get {
                return ResourceManager.GetString("thisWillImport2", resourceCulture);
            }
        }
    }
}
